-- Row-level security: the fourth layer of tenant isolation.
-- See docs/SECURITY.md §1 Layer 3. Generated by scripts/gen-rls-migration.mjs.
--
-- The application connects as a role with neither SUPERUSER nor BYPASSRLS, so
-- these policies apply to it. FORCE ROW LEVEL SECURITY is deliberately NOT set:
-- the table owner stays exempt so migrations, seeding and retention jobs keep
-- cross-tenant access. Those run offline as a privileged role and are not the
-- surface being defended -- a leaked request handler is.

-- ---------------------------------------------------------------------------
-- STRICT: unset tenant => zero rows. Fails closed.
-- ---------------------------------------------------------------------------
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "audit_logs";
CREATE POLICY tenant_isolation ON "audit_logs"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "contact_attempts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "contact_attempts";
CREATE POLICY tenant_isolation ON "contact_attempts"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "documents" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "documents";
CREATE POLICY tenant_isolation ON "documents"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "ehr_links" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ehr_links";
CREATE POLICY tenant_isolation ON "ehr_links"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "intake_batches" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "intake_batches";
CREATE POLICY tenant_isolation ON "intake_batches"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "intake_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "intake_items";
CREATE POLICY tenant_isolation ON "intake_items"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "patient_match_candidates" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "patient_match_candidates";
CREATE POLICY tenant_isolation ON "patient_match_candidates"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "patients" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "patients";
CREATE POLICY tenant_isolation ON "patients"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "payers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "payers";
CREATE POLICY tenant_isolation ON "payers"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "referral_activities" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referral_activities";
CREATE POLICY tenant_isolation ON "referral_activities"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "referral_status_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referral_status_history";
CREATE POLICY tenant_isolation ON "referral_status_history"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "referral_touch_metrics" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referral_touch_metrics";
CREATE POLICY tenant_isolation ON "referral_touch_metrics"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "referrals" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referrals";
CREATE POLICY tenant_isolation ON "referrals"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "referring_organizations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referring_organizations";
CREATE POLICY tenant_isolation ON "referring_organizations"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "referring_providers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referring_providers";
CREATE POLICY tenant_isolation ON "referring_providers"
  USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

-- ---------------------------------------------------------------------------
-- BOOTSTRAP: readable while resolving which tenant a request belongs to,
-- restricted the moment a tenant is bound.
-- ---------------------------------------------------------------------------
ALTER TABLE "invitations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invitations";
CREATE POLICY tenant_isolation ON "invitations"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  );

ALTER TABLE "memberships" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "memberships";
CREATE POLICY tenant_isolation ON "memberships"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  );

ALTER TABLE "organization_settings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "organization_settings";
CREATE POLICY tenant_isolation ON "organization_settings"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  );

ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "organizations";
CREATE POLICY tenant_isolation ON "organizations"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "id" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "id" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  );

ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "roles";
CREATE POLICY tenant_isolation ON "roles"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  );

ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "sessions";
CREATE POLICY tenant_isolation ON "sessions"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  )
  WITH CHECK (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR "organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
  );

-- ---------------------------------------------------------------------------
-- Join table: no organization_id of its own, scoped through its membership.
-- ---------------------------------------------------------------------------
ALTER TABLE "membership_roles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "membership_roles";
CREATE POLICY tenant_isolation ON "membership_roles"
  USING (
    NULLIF(current_setting('app.current_org_id', true), '') IS NULL
    OR EXISTS (
      SELECT 1 FROM memberships m
      WHERE m."id" = "membershipId"
        AND m."organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid
    )
  );

-- ---------------------------------------------------------------------------
-- Append-only tables. Application discipline is not a guarantee:
-- docs/OPEN-QUESTIONS.md A-8.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION refuse_mutation() RETURNS trigger AS $$
BEGIN
  -- The owner retains UPDATE/DELETE so retention purges and restores remain
  -- possible. The application role never does.
  IF current_user = 'referral_app' THEN
    RAISE EXCEPTION '% is append-only; % is not permitted', TG_TABLE_NAME, TG_OP
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

REVOKE UPDATE, DELETE ON "audit_logs" FROM referral_app;
DROP TRIGGER IF EXISTS refuse_mutation ON "audit_logs";
CREATE TRIGGER refuse_mutation BEFORE UPDATE OR DELETE ON "audit_logs"
  FOR EACH ROW EXECUTE FUNCTION refuse_mutation();

REVOKE UPDATE, DELETE ON "referral_status_history" FROM referral_app;
DROP TRIGGER IF EXISTS refuse_mutation ON "referral_status_history";
CREATE TRIGGER refuse_mutation BEFORE UPDATE OR DELETE ON "referral_status_history"
  FOR EACH ROW EXECUTE FUNCTION refuse_mutation();

REVOKE UPDATE, DELETE ON "referral_activities" FROM referral_app;
DROP TRIGGER IF EXISTS refuse_mutation ON "referral_activities";
CREATE TRIGGER refuse_mutation BEFORE UPDATE OR DELETE ON "referral_activities"
  FOR EACH ROW EXECUTE FUNCTION refuse_mutation();

-- Ensure the app role can reach tables created by this and future migrations.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO referral_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO referral_app;
REVOKE UPDATE, DELETE ON "audit_logs" FROM referral_app;
REVOKE UPDATE, DELETE ON "referral_status_history" FROM referral_app;
REVOKE UPDATE, DELETE ON "referral_activities" FROM referral_app;
