-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('CLINICAL_CONTENT_VIEWED', 'CLINICAL_CONTENT_CREATED', 'CLINICAL_CONTENT_DELETED', 'CASE_SAVED', 'CASE_DELETED', 'MEMBER_INVITED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED', 'SETTINGS_CHANGED', 'SIGNED_IN', 'SIGNED_OUT', 'ADMIN_METRICS_VIEWED');

-- CreateTable
CREATE TABLE "audit_events" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "userId" UUID,
    "action" "AuditAction" NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT,
    "ipHash" TEXT,
    "userAgent" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "audit_events_organizationId_createdAt_idx" ON "audit_events"("organizationId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "audit_events_organizationId_action_createdAt_idx" ON "audit_events"("organizationId", "action", "createdAt" DESC);

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Row-level security for the audit log.
--
-- Append-only: INSERT and SELECT policies exist, UPDATE and DELETE do not,
-- so PostgreSQL refuses both even for the application role. Generated by
-- scripts/gen-rls-migration.mjs.
ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_events" FORCE ROW LEVEL SECURITY;
-- APPEND-ONLY: insert and read within the tenant; no UPDATE or
-- DELETE policy exists, so PostgreSQL refuses both outright.
CREATE POLICY "audit_events_insert" ON "audit_events" FOR INSERT WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
CREATE POLICY "audit_events_select" ON "audit_events" FOR SELECT USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
