-- Row-level security.
--
-- Generated by scripts/gen-rls-migration.mjs. Do not edit by hand.
--
-- This is the backstop beneath the application-level tenant filter, and it
-- only works if the application connects as a role that is NOT a superuser
-- and does NOT have BYPASSRLS. See docs/SECURITY.md.

ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "organizations" FORCE ROW LEVEL SECURITY;
-- BOOTSTRAP: identity, reached by secret token before a tenant is known.
CREATE POLICY "organizations_bootstrap" ON "organizations" USING (true) WITH CHECK (true);

ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
-- BOOTSTRAP: identity, reached by secret token before a tenant is known.
CREATE POLICY "users_bootstrap" ON "users" USING (true) WITH CHECK (true);

ALTER TABLE "organization_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "organization_members" FORCE ROW LEVEL SECURITY;
-- BOOTSTRAP: identity, reached by secret token before a tenant is known.
CREATE POLICY "organization_members_bootstrap" ON "organization_members" USING (true) WITH CHECK (true);

ALTER TABLE "invitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invitations" FORCE ROW LEVEL SECURITY;
-- BOOTSTRAP: identity, reached by secret token before a tenant is known.
CREATE POLICY "invitations_bootstrap" ON "invitations" USING (true) WITH CHECK (true);

ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" FORCE ROW LEVEL SECURITY;
-- BOOTSTRAP: identity, reached by secret token before a tenant is known.
CREATE POLICY "sessions_bootstrap" ON "sessions" USING (true) WITH CHECK (true);

ALTER TABLE "password_reset_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "password_reset_tokens" FORCE ROW LEVEL SECURITY;
-- BOOTSTRAP: identity, reached by secret token before a tenant is known.
CREATE POLICY "password_reset_tokens_bootstrap" ON "password_reset_tokens" USING (true) WITH CHECK (true);

ALTER TABLE "code_datasets" ENABLE ROW LEVEL SECURITY;
-- REFERENCE: global procedure-code data, readable by every tenant.
-- Writable only by the table owner (the importer). RLS is not FORCEd
-- here so that the owner can load a dataset; the application role is
-- not the owner and is confined to SELECT by this policy.
CREATE POLICY "code_datasets_read" ON "code_datasets" FOR SELECT USING (true);

ALTER TABLE "procedure_codes" ENABLE ROW LEVEL SECURITY;
-- REFERENCE: global procedure-code data, readable by every tenant.
-- Writable only by the table owner (the importer). RLS is not FORCEd
-- here so that the owner can load a dataset; the application role is
-- not the owner and is confined to SELECT by this policy.
CREATE POLICY "procedure_codes_read" ON "procedure_codes" FOR SELECT USING (true);

ALTER TABLE "procedure_code_attributes" ENABLE ROW LEVEL SECURITY;
-- REFERENCE: global procedure-code data, readable by every tenant.
-- Writable only by the table owner (the importer). RLS is not FORCEd
-- here so that the owner can load a dataset; the application role is
-- not the owner and is confined to SELECT by this policy.
CREATE POLICY "procedure_code_attributes_read" ON "procedure_code_attributes" FOR SELECT USING (true);

ALTER TABLE "procedure_code_relationships" ENABLE ROW LEVEL SECURITY;
-- REFERENCE: global procedure-code data, readable by every tenant.
-- Writable only by the table owner (the importer). RLS is not FORCEd
-- here so that the owner can load a dataset; the application role is
-- not the owner and is confined to SELECT by this policy.
CREATE POLICY "procedure_code_relationships_read" ON "procedure_code_relationships" FOR SELECT USING (true);

ALTER TABLE "documentation_rules" ENABLE ROW LEVEL SECURITY;
-- REFERENCE: global procedure-code data, readable by every tenant.
-- Writable only by the table owner (the importer). RLS is not FORCEd
-- here so that the owner can load a dataset; the application role is
-- not the owner and is confined to SELECT by this policy.
CREATE POLICY "documentation_rules_read" ON "documentation_rules" FOR SELECT USING (true);

ALTER TABLE "coding_queries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coding_queries" FORCE ROW LEVEL SECURITY;
-- TENANT: reachable only within the bound organization.
CREATE POLICY "coding_queries_tenant" ON "coding_queries" USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "coding_query_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coding_query_messages" FORCE ROW LEVEL SECURITY;
-- TENANT: reachable only within the bound organization.
CREATE POLICY "coding_query_messages_tenant" ON "coding_query_messages" USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "saved_cases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "saved_cases" FORCE ROW LEVEL SECURITY;
-- TENANT: reachable only within the bound organization.
CREATE POLICY "saved_cases_tenant" ON "saved_cases" USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "usage_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_events" FORCE ROW LEVEL SECURITY;
-- TENANT: reachable only within the bound organization.
CREATE POLICY "usage_events_tenant" ON "usage_events" USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "ai_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_requests" FORCE ROW LEVEL SECURITY;
-- TENANT: reachable only within the bound organization.
CREATE POLICY "ai_requests_tenant" ON "ai_requests" USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions" FORCE ROW LEVEL SECURITY;
-- TENANT: reachable only within the bound organization.
CREATE POLICY "subscriptions_tenant" ON "subscriptions" USING ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK ("organizationId" = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
